name: Node.js CI

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3.5.0
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: 'npm'

      - run: node --version
      - run: npm --version
      - run: npm cache clean --force

      - name: Install Node Dependencies
        run: npm install --no-package-lock

      - name: Lint
        run: npm run lint

      - name: Build Chrome
        run: npm run build:chrome

      - name: Build Firefox
        run: npm run build:firefox

      - name: Post Lint Firefox
        run: npm run manifest-lint

      - name: Build User-Script
        run: npm run build:userscript

      - name: Get Version Tag
        id: get_tag
        run: echo "RELEASE_TAG=v1.0.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: Release ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false

      - name: Upload Chrome Build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/chrome.zip
          asset_name: chrome.zip
          asset_content_type: application/zip

      - name: Upload Firefox Build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/firefox.zip
          asset_name: firefox.zip
          asset_content_type: application/zip

      - name: Upload Userscript Build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/userscript.user.js
          asset_name: userscript.user.js
          asset_content_type: application/javascript
